#!/bin/sh

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

[ -x /usr/bin/makedumpfile ] || exit 0

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/bin

copy_exec /usr/bin/makedumpfile /bin
